### ISSUE TITLE
confused about installation

### ISSUE THREAD

**Issue by flip111** [Kwpolska/python-project-template#1]
> 1. Create the repository for the project on GitHub and enable it on Travis CI.

I have a local repository with gitlab, so i skipped this step for now. Not sure what can go wrong later because of this step being skipped.

> 2. Install PyPT’s ``requirements.txt`` (in a virtualenv) and run ``cookiecutter
>    /path/to/your/clone/of/python-project-template`` (in your Projects/git
>    directory/wherever you hold your projects).
>    .

thought at first i was suppose to work off this git repo so i cloned with `git clone https://github.com/Kwpolska/python-project-template.git my_project`, only found out later that cookiecutter creates a new directory, so had to start over.

not sure where to install the venv directory so i just put it somewhere

thought i was suppose to cd into `python-project-template` first, but i just need to stay in the directory where i want my project to be

> 3. Modify all documents: match under/overlines, write real content.

what documents are you talking about? i looked into the docs folder only plain text files there which can't under of overline. Didn't see underscores either.

> 4. Copy: (when using the included ``release`` script, it happens automatically)
> 
>    1. ``/docs/README.rst`` to ``/README.rst`` and ``/README``
>    2. ``/docs/CHANGELOG.rst`` to ``/CHANGELOG.rst``
> 

Release script ask me for version number but i already fill this in with cookiecutter, why again? Script goes wrong since it's looking for a .git directory which is not there yet. Can i do without github but with .git dir? Since it's accessing version control i think it wants to make a new version, which doesn't make sense yet. So step 4 is optional when using release script? Release script tries to continue more stuff is going wrong

```
*** Chris Warrick’s Release Scripts (PyPT)
Version number: cleanup:2: no matches found: **/__pycache__
fatal: Not a git repository (or any parent up to mount point /home/flip111)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./release:101: no such file or directory: /home/flip111/myproject/.git/kwrs-1505400046
sed: can't read /home/flip111/myproject/.git/kwrs-1505400046: No such file or directory
./release:120: no such file or directory: /home/flip111/myproject/.git/kwrs-1505400046
UTF8 locale not supported.
Traceback (most recent call last):
  File ".pypt/commitlog", line 120, in <module>
    sys.exit(main())
  File ".pypt/commitlog", line 90, in main
    with open(filename) as fh:
IOError: [Errno 2] No such file or directory: '/home/flip111/myproject/.git/kwrs-1505400046'
Replacing versions and dates in files...
Generating locales...
Importing...
Running tests...
./release:159: command not found: pytest
ERROR: Tests failed.  Fix your code or don't come back.
```

> 5. Modify ``/.pypt/config``.

not sure what i need to modify here, everything already seems to be filled in with cookiecutter, what should i put for the locale though?

> 6. Generate a `GitHub Personal Access Token <https://github.com/settings/tokens>`_
>    in the ``repo`` scope and write it to a ``/.pypt/gh-token`` file. You may
>    reuse tokens between different repos running PyPT.

not using github, starting to doubt if i can even use python-project-template without github

> 7. Customize ``/setup.py`` to your liking.  You should pay attention to the
>    classifiers and the commented-out parts.
> 
>    If you’re making a **console app** with scripts/executables, uncomment the
>    ``entry_points`` sample as-is.  If you’re making a **GUI app**, change
>    ``console_scripts`` to ``gui_scripts``. In both cases, you should customize
>    ``__main__.py`` to your liking. Remember that ``main()`` must take no
>    positional/non-default arguments! If you do not want to create scripts,
>    remove ``__main__.py``.
> 

can't cookiecutter just ask me if i want a console, gui or no app at all ?

> 8. Customize ``requirements.txt``.

why? i haven't even started developing yet. Why is this part of the setup?

> 9. **Extras:** If you are using **PyQt or PySide**, make sure to put your UI code in a
>    ``ui`` submodule.  Copy the ``pypt-extras/Qt/resources.py`` file to that
>    submodule, even if you are not using resources now. Make sure to create a
>    ``.pro`` file with your sources and locales. If you want to use the **AUR**
>    package updater, see the `AUR support`_ section.

skipping

> 10. Remove the ``pypt-extras`` directory if you don’t need anything else from it.

not sure what it is or what i would need from it, skipping this step

> 11. If you have a ``PYPT-UPDATE`` script, add your new project to the list
>     there.  If not, you may want to copy it from the repository root and set it up.

don't have it, unless it comes by default

> 12. Run the following commands::
> 
>         source .pypt/config
>         git init
>         git remote add origin git@github.com:$GITUSER/$GITREPO
>         git add *
>         git commit -sm 'initial commit via @Kwpolska’s Python Project Template'
>         git push -u origin master

`source .pypt/config` what's this?

so this will be the initial commit? then what about the release script earlier?

---
the steps are not "easy". I think i'm missing some background information on some steps (but there are no links to where i can find out about it). But also there are some problems with instructions and release script. what's aur_email in cookiecutter anyway? I HAVE TO fill in this email and i don't know what it is for. Why can't the defaults be empty? Or how can i enter an empty string in cookiecutter?

I think for now i will do without this project template and just figure things out as i go.

**Comment by Kwpolska** [comment]
I understand it may not be easy for everyone. Sometimes when doing things like those you just assume everyone knows the same things as you do.

* Some things are caused by cookiecutter limitations, the default values are one of them.
* I can automate entry point creation, actually. That will happen in a future version.
* `aur_email` is used for AUR support.
* GitHub is used for automating GitHub Releases creation and a few links here or there.
---

* Step 3: I mean anything under `docs`
* Step 4: do not use `release` yet. Perhaps that was unclear.
* Step 5: Python versions supported, locale type (you should use `none` if you have no idea
* 
* Step 10: `pypt-extras` was mentioned in step 9.
* Step 11: as the description says, it’s in the python-project-template repo root.

I’ll try to restructure the documentation and see how it goes. I should probably also document some of the peculiar decisions taken that work for me, but may not be enough for others.
