### ISSUE TITLE
Make this a cookiecutter template?

### ISSUE THREAD

**Issue by espoelstra** [Kwpolska/python-project-template#3]
Seems like some of the stuff you had trouble automating could be completed using cookiecutter.

**Comment by Kwpolska** [comment]
For example? I used as many cookiecutter features I could find documentation for and that made sense, at least at the time when the cookiecutter conversion was made.

**Comment by espoelstra** [comment]
Ahhh, I believe the issue was not realizing it might be possible to seed the answers to the project creation template rather than going through the entire questionnaire.
